import { zodToJsonSchema } from "zod-to-json-schema";

import { CURRENT_SCHEMA_VERSION } from "../db/schema/version";
import { ERROR_STATUS } from "../domain/errors";
import { AdminCreateUserBody, AdminDeleteUserBody } from "../routes/admin";
import { ChangePasswordBody, SignInBody } from "../routes/auth";
import { ProfileUpdateBody } from "../routes/profile";
import { TokenCreateBody } from "../routes/tokens";

/**
 * The published API contract. Request bodies come from the same Zod schemas the
 * routes validate against, so the two cannot drift. Regenerated by
 * `pnpm openapi:write`; CI fails if the committed `openapi.yaml` differs
 * (plan.md section 11).
 *
 * This is a hand-assembled document rather than `@hono/zod-openapi` output —
 * recorded as a deviation in plan.md section 0. Every route's request schema is
 * still Zod-sourced.
 */

type Json = Record<string, unknown>;

function bodySchema(schema: Parameters<typeof zodToJsonSchema>[0]): Json {
  return zodToJsonSchema(schema, {
    target: "openApi3",
    $refStrategy: "none",
  }) as Json;
}

const ErrorSchema: Json = {
  type: "object",
  required: ["code", "message"],
  additionalProperties: false,
  properties: {
    code: { type: "string", enum: Object.keys(ERROR_STATUS) },
    message: { type: "string" },
    details: { description: "Optional structured detail" },
  },
};

function jsonBody(schema: Json, required = true): Json {
  return {
    required,
    content: { "application/json": { schema } },
  };
}

function jsonResponse(description: string, schema: Json): Json {
  return { description, content: { "application/json": { schema } } };
}

function errorResponse(description: string): Json {
  return jsonResponse(description, { $ref: "#/components/schemas/Error" });
}

const emptyResponse = (description: string): Json => ({ description });

const idParam: Json = {
  name: "id",
  in: "path",
  required: true,
  schema: { type: "string" },
};

/** A `POST /admin/users/{id}/<verb>` action that returns 204 and no body. */
function adminAction(
  operationId: string,
  summary: string,
  description: string,
): Json {
  return {
    post: {
      operationId,
      summary,
      description,
      parameters: [idParam],
      responses: {
        "204": emptyResponse("Done (idempotent)"),
        "401": errorResponse("Not authenticated"),
        "403": errorResponse("Admin role required"),
        "404": errorResponse("No such user"),
        "422": errorResponse("This is the last active admin"),
      },
    },
  };
}

export function buildOpenApiDocument(): Json {
  return {
    openapi: "3.1.0",
    info: {
      title: "Chotu API",
      version: "0.1.0",
      description:
        "Chotu is an open-source, self-hostable vehicle fuel log. This is the M1 " +
        "auth surface. Every error uses the shared Error schema: a stable `code`, " +
        "a human `message`, and optional `details`.",
      license: { name: "AGPL-3.0-only", identifier: "AGPL-3.0-only" },
    },
    paths: {
      "/healthz": {
        get: {
          operationId: "getHealth",
          summary: "Liveness and applied schema version",
          description: "Unauthenticated. Reports that the API is up.",
          security: [],
          responses: {
            "200": jsonResponse("The service is up", {
              type: "object",
              required: ["status", "schemaVersion"],
              properties: {
                status: { type: "string", const: "ok" },
                schemaVersion: { type: "integer", const: CURRENT_SCHEMA_VERSION },
              },
            }),
          },
        },
      },
      "/auth/sign-in": {
        post: {
          operationId: "signIn",
          summary: "Sign in with email and password",
          description:
            "Returns a session credential and sets an HttpOnly cookie. A wrong " +
            "email or password returns the same generic 401. Rate limited per IP " +
            "and per account.",
          security: [],
          requestBody: jsonBody(bodySchema(SignInBody)),
          responses: {
            "200": jsonResponse("Signed in", {
              type: "object",
              required: ["user", "session", "expiresAt"],
              properties: {
                user: { $ref: "#/components/schemas/PublicUser" },
                session: { type: "string", description: "Session credential" },
                expiresAt: { type: "string", format: "date-time" },
              },
            }),
            "400": errorResponse("Malformed body"),
            "401": errorResponse("Wrong email or password"),
            "429": errorResponse("Rate limited; see Retry-After"),
          },
        },
      },
      "/auth/sign-out": {
        post: {
          operationId: "signOut",
          summary: "Revoke the current session",
          description: "Requires authentication. Clears the session cookie.",
          responses: {
            "204": emptyResponse("Signed out"),
            "401": errorResponse("Not authenticated"),
          },
        },
      },
      "/auth/change-password": {
        post: {
          operationId: "changePassword",
          summary: "Change the password by supplying the current one",
          description:
            "Requires authentication (a session or an API token). Clears the " +
            "must-change-password flag on success.",
          requestBody: jsonBody(bodySchema(ChangePasswordBody)),
          responses: {
            "204": emptyResponse("Password changed"),
            "400": errorResponse("Malformed body"),
            "401": errorResponse("Current password is wrong or not authenticated"),
          },
        },
      },
      "/auth/me": {
        get: {
          operationId: "getMe",
          summary: "The signed-in user",
          description:
            "Requires authentication. A must-change-password user is refused " +
            "with 403 until the password is changed.",
          responses: {
            "200": jsonResponse("The current user", {
              type: "object",
              required: ["user"],
              properties: {
                user: { $ref: "#/components/schemas/PublicUser" },
              },
            }),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Password change required"),
          },
        },
      },
      "/profile": {
        get: {
          operationId: "getProfile",
          summary: "The caller's own profile",
          description:
            "Requires authentication. Returns display name, unit system, IANA " +
            "time zone, and the read-only USD currency code.",
          responses: {
            "200": jsonResponse("The caller's profile", {
              type: "object",
              required: ["profile"],
              properties: {
                profile: { $ref: "#/components/schemas/Profile" },
              },
            }),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Password change required"),
          },
        },
        patch: {
          operationId: "updateProfile",
          summary: "Update the caller's own profile",
          description:
            "Requires authentication. Any subset of display name, unit system, " +
            "and time zone. `currency_code` is read-only USD in M1. A unit-system " +
            "change does not rewrite stored data.",
          requestBody: jsonBody(bodySchema(ProfileUpdateBody)),
          responses: {
            "200": jsonResponse("The updated profile", {
              type: "object",
              required: ["profile"],
              properties: {
                profile: { $ref: "#/components/schemas/Profile" },
              },
            }),
            "400": errorResponse("Malformed body or no field to change"),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Password change required"),
          },
        },
        delete: {
          operationId: "deleteOwnAccount",
          summary: "Delete the caller's own account",
          description:
            "Requires authentication. Removes the caller's vehicles, fuel " +
            "entries, tokens, sessions, and identities. Recorded in the audit " +
            "log without personal content. The last active admin cannot delete " +
            "their own account.",
          responses: {
            "204": emptyResponse("Account deleted"),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Password change required"),
            "422": errorResponse("This is the last active admin"),
          },
        },
      },
      "/tokens": {
        get: {
          operationId: "listApiTokens",
          summary: "List the caller's API tokens",
          description: "Requires authentication. Never returns the token value.",
          responses: {
            "200": jsonResponse("The caller's tokens", {
              type: "object",
              required: ["tokens"],
              properties: {
                tokens: {
                  type: "array",
                  items: { $ref: "#/components/schemas/ApiToken" },
                },
              },
            }),
            "401": errorResponse("Not authenticated"),
          },
        },
        post: {
          operationId: "createApiToken",
          summary: "Create an API token",
          description:
            "Requires authentication. The plaintext token is returned once and " +
            "then only stored hashed.",
          requestBody: jsonBody(bodySchema(TokenCreateBody), false),
          responses: {
            "201": jsonResponse("The new token, shown once", {
              type: "object",
              required: ["token", "note"],
              properties: {
                token: { type: "string" },
                note: { type: "string" },
              },
            }),
            "401": errorResponse("Not authenticated"),
          },
        },
      },
      "/tokens/{id}": {
        delete: {
          operationId: "revokeApiToken",
          summary: "Revoke one of the caller's API tokens",
          description: "Requires authentication. A token the caller does not own is 404.",
          parameters: [
            {
              name: "id",
              in: "path",
              required: true,
              schema: { type: "string" },
            },
          ],
          responses: {
            "204": emptyResponse("Revoked (or already revoked)"),
            "401": errorResponse("Not authenticated"),
            "404": errorResponse("No such token for this user"),
          },
        },
      },
      "/admin/users": {
        get: {
          operationId: "adminListUsers",
          summary: "List every account",
          description:
            "Admin only. Accounts, roles, status, and a vehicle count. No fuel " +
            "entry data is ever included (INV-9).",
          responses: {
            "200": jsonResponse("Every account, newest first", {
              type: "object",
              required: ["users"],
              properties: {
                users: {
                  type: "array",
                  items: { $ref: "#/components/schemas/AdminUserListItem" },
                },
              },
            }),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Admin role required"),
          },
        },
        post: {
          operationId: "adminCreateUser",
          summary: "Create an account directly",
          description:
            "Admin only (FR-8.3). Omit `password` to get a one-time " +
            "set-password link in the response instead.",
          requestBody: jsonBody(bodySchema(AdminCreateUserBody)),
          responses: {
            "201": jsonResponse("The new account", {
              type: "object",
              required: ["user"],
              properties: {
                user: { $ref: "#/components/schemas/AdminUserListItem" },
                setPasswordToken: {
                  type: "string",
                  description: "Present when no password was supplied",
                },
                note: { type: "string" },
              },
            }),
            "400": errorResponse("Malformed body"),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Admin role required"),
            "409": errorResponse("Email already registered"),
          },
        },
      },
      "/admin/users/{id}": {
        get: {
          operationId: "adminGetUser",
          summary: "One account with security metadata",
          description:
            "Admin only. Adds last sign-in, linked identities, and the active " +
            "API-token count. No fuel entry data is ever included (INV-9).",
          parameters: [idParam],
          responses: {
            "200": jsonResponse("The account", {
              type: "object",
              required: ["user"],
              properties: {
                user: { $ref: "#/components/schemas/AdminUserDetail" },
              },
            }),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Admin role required"),
            "404": errorResponse("No such user"),
          },
        },
        delete: {
          operationId: "adminDeleteUser",
          summary: "Delete an account and all its data",
          description:
            "Admin only (FR-8.6). `confirmEmail` must equal the target's " +
            "email. Cascades vehicles, entries, tokens, sessions, identities. " +
            "Refused for the last active admin (INV-6).",
          parameters: [idParam],
          requestBody: jsonBody(bodySchema(AdminDeleteUserBody)),
          responses: {
            "204": emptyResponse("Deleted"),
            "400": errorResponse("Missing or mismatched confirmEmail"),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Admin role required"),
            "404": errorResponse("No such user"),
            "422": errorResponse("This is the last active admin"),
          },
        },
      },
      "/admin/users/{id}/deactivate": adminAction(
        "adminDeactivateUser",
        "Deactivate an account",
        "Admin only (FR-8.4). Cuts the user's sessions and API tokens " +
          "immediately. Refused for the last active admin (INV-6).",
      ),
      "/admin/users/{id}/reactivate": adminAction(
        "adminReactivateUser",
        "Reactivate an account",
        "Admin only (FR-8.4).",
      ),
      "/admin/users/{id}/grant-admin": adminAction(
        "adminGrantAdmin",
        "Grant the admin role",
        "Admin only (FR-8.7).",
      ),
      "/admin/users/{id}/revoke-admin": adminAction(
        "adminRevokeAdmin",
        "Revoke the admin role",
        "Admin only (FR-8.7). Refused for the last active admin (INV-6).",
      ),
      "/admin/users/{id}/reset": {
        post: {
          operationId: "adminTriggerReset",
          summary: "Trigger a password reset for an account",
          description:
            "Admin only (FR-8.5). Issues a reset link. The link is returned in " +
            "the response when email is not configured (R-2 interim).",
          parameters: [idParam],
          responses: {
            "200": jsonResponse("Reset issued", {
              type: "object",
              required: ["sent"],
              properties: {
                sent: { type: "boolean" },
                resetToken: {
                  type: "string",
                  description: "Present when email is not configured",
                },
                note: { type: "string" },
              },
            }),
            "401": errorResponse("Not authenticated"),
            "403": errorResponse("Admin role required"),
            "404": errorResponse("No such user"),
          },
        },
      },
      "/openapi.yaml": {
        get: {
          operationId: "getOpenApi",
          summary: "This document",
          description: "Unauthenticated.",
          security: [],
          responses: { "200": emptyResponse("The OpenAPI document, as YAML") },
        },
      },
    },
    components: {
      securitySchemes: {
        bearerAuth: { type: "http", scheme: "bearer" },
        cookieAuth: { type: "apiKey", in: "cookie", name: "chotu_session" },
      },
      schemas: {
        Error: ErrorSchema,
        PublicUser: {
          type: "object",
          required: ["id", "email", "displayName", "role", "mustChangePassword"],
          properties: {
            id: { type: "string" },
            email: { type: "string", format: "email" },
            displayName: { type: "string" },
            role: { type: "string", enum: ["user", "admin"] },
            mustChangePassword: { type: "boolean" },
          },
        },
        Profile: {
          type: "object",
          required: [
            "id",
            "email",
            "displayName",
            "role",
            "unitSystem",
            "timeZone",
            "currencyCode",
            "mustChangePassword",
          ],
          properties: {
            id: { type: "string" },
            email: { type: "string", format: "email" },
            displayName: { type: "string" },
            role: { type: "string", enum: ["user", "admin"] },
            unitSystem: { type: "string", enum: ["imperial", "metric"] },
            timeZone: { type: "string", description: "IANA time zone" },
            currencyCode: {
              type: "string",
              const: "USD",
              description: "Read-only in M1",
            },
            mustChangePassword: { type: "boolean" },
          },
        },
        AdminUserListItem: {
          type: "object",
          required: [
            "id",
            "email",
            "displayName",
            "role",
            "status",
            "createdAt",
            "vehicleCount",
          ],
          properties: {
            id: { type: "string" },
            email: { type: "string", format: "email" },
            displayName: { type: "string" },
            role: { type: "string", enum: ["user", "admin"] },
            status: { type: "string", enum: ["active", "deactivated"] },
            createdAt: { type: "string", format: "date-time" },
            vehicleCount: { type: "integer", minimum: 0 },
          },
        },
        AdminUserDetail: {
          allOf: [
            { $ref: "#/components/schemas/AdminUserListItem" },
            {
              type: "object",
              required: [
                "lastSignInAt",
                "linkedIdentities",
                "activeTokenCount",
              ],
              properties: {
                lastSignInAt: {
                  type: ["string", "null"],
                  format: "date-time",
                },
                linkedIdentities: {
                  type: "array",
                  items: { type: "string" },
                },
                activeTokenCount: { type: "integer", minimum: 0 },
              },
            },
          ],
        },
        ApiToken: {
          type: "object",
          required: ["id", "label", "createdAt", "lastUsedAt", "expiresAt", "revokedAt"],
          properties: {
            id: { type: "string" },
            label: { type: ["string", "null"] },
            createdAt: { type: "string", format: "date-time" },
            lastUsedAt: { type: ["string", "null"], format: "date-time" },
            expiresAt: { type: ["string", "null"], format: "date-time" },
            revokedAt: { type: ["string", "null"], format: "date-time" },
          },
        },
      },
    },
    security: [{ bearerAuth: [] }, { cookieAuth: [] }],
  };
}
